#!/bin/bash
file="$1"

ext=$(echo "$file" | awk -F. '{print $NF}')

#if the input is the current directory open it in vs code
if [[ "$file" == "." || -d "$file" ]]; then
    # If the insiders version is installed open that one.
    # Otherwise open in normal vscode
    if [[ "$(command -v code-insiders)"]]; then
      code-insiders "$file" &> /dev/null & exit 0
    else
      code "$file" &> /dev/null & exit 0
    fi
fi

# Open uri's with xdg-open
if [[ ! -f "$file" ]]; then
  exec /usr/bin/xdg-open "$file"
fi

# read the major and minor mimetype
IFS='/' read -r major minor < <(file -ib "$file" 2>/dev/null | cut -d ';' -f 1)

# check for a specific case
case "$major/$minor" in
  text/html)       $BROWSER "$file" &>/dev/null & exit 0 ;;
  application/pdf) zathura "$file"  &>/dev/null & exit 0 ;;
esac

# open specific type of files based on there extension
case "$ext" in
    pka) packettracer "$file" &>/dev/null & exit 0;;
    odt) onlyoffice-desktopeditors "$file" &>/dev/null & exit 0;;
    docx) onlyoffice-desktopeditors "$file" &>/dev/null & exit 0;;
    md)   typora "$file" &>/dev/null & exit 0;;
esac

# check for just a major match
case "$major" in
  image) feh "$file"        &>/dev/null & exit 0 ;;
  text)  st -e vim "$file" &>/dev/null & exit 0 ;;
  video) vlc "$file"           &>/dev/null & exit 0 ;;
esac


echo "No match found defaulting to xdg-open"

exec /usr/bin/xdg-open "$file"
