#!/bin/bash
echo "Printing current power usage"

#grab, convert and print the current power usage, current and voltage
(awk '{print $1*10^-6 " V"}' /sys/class/power_supply/BAT0/voltage_now && awk '{print $1*10^-6 " W"}' /sys/class/power_supply/BAT0/power_now) | awk '{a[$2]=$1}END{print a["W"], "W"; print a["V"], "V";print a["W"]/a["V"], "A"}'

#pretty print the output
echo ""

#grab; convert and print the current battery level and total battery size
(awk '{print $1*10^-6 " V"}' /sys/class/power_supply/BAT0/energy_now && awk '{print $1*10^-6 " W"}' /sys/class/power_supply/BAT0/energy_full) | awk '{a[NR-1]=$1}END{print "Charge",a[0]"/"a[1], "Wh"}'
