#!/usr/bin/env bash

# MIT License
# 
# Copyright (c) 2020 Tom Meyers
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
mirrors=273

mirrorfile=$(curl https://www.archlinux.org/mirrorlist/all/)
mirrors=$(echo "$mirrorfile" | awk '$0 ~ /^Server|^#Server/{print $0}' | wc -l)

echo "You have $(awk '$0 ~ /^Server|^#Server/{print $0}' /etc/pacman.d/mirrorlist | wc -l) servers in your /etc/pacmand.d/mirrorlist"
read -r -p "You need to manually make sure your mirrorlist contains all servers otherwise copy over a backup found in /etc/pacman.d/*.backup. Understood (Y/n)" result

# abort if the user requests it
if [[ "$result" == "n" || "$result" == "N" ]]; then
    exit 0
fi  

datetime=$(date| tr ' ' '-')

sudo cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist"$datetime".backup

ls /etc/pacman.d/mirrorlist*

echo -e "$mirrorfile" > moment
sudo mv moment /etc/pacman.d/

sudo sed -i 's/^#Server/Server/' /etc/pacman.d/moment

echo "Finding the top $mirrors mirrors and moving them to the top"

sudo sh -c "rankmirrors -n $mirrors /etc/pacman.d/moment > /etc/pacman.d/mirrorlist"

echo "Done finding the mirrors"

echo "Test pacman to check if everything still works"

echo "If nothing works run this command:"

echo "mv /etc/pacman.d/mirrorlist$datetime.backup /etc/pacman.d/mirrolist"


