#!/bin/bash

rofidir="/usr/share/tos-rofi"
prompt=$(find "$rofidir" -exec basename {} \; | awk "!/^askpass/" | sort)

sol=$(echo -e "$prompt" | rofi -dmenu -p 'Select subscript' -font 'Fira Code 10')

eval "$rofidir/$sol"
