#!/bin/bash

# TOS is the Tom OS update script. This script manages everything for maintaining and upgrading.
# To understand how to install the software go to https://github.com/F0Xedb/helper-scripts
# Archinstall and dialogarchinstall are scripts that install arch from scratch and also install custom software to more personalise the os
# Once you have installed arch and have cloned the helper-scripts into a $PATH file you will have the tool TOS.
# This tool is a wrapper around arch based tools.
# It can install packages from the repo's and AUR. It also aids with ssh, networking, updating, installing software and more.
# It basically wraps multiple commands into one simple to use command.

RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;35m'
ORANGE='\033[1;33m'
NC='\033[0m' # No Color

export SUDO_ASKPASS='$HOME/bin/rofi/askpass'
name=$(basename "$0")
themefile="$HOME/.config/tos/theme"
extended="$HOME/bin/tos-helper"



case "$1" in
    ""|"-h"|"--help")
        source $extended/help.sh
    ;;
    "-u"|"--update")
        source $extended/update.sh
    ;;
    "-S"*|"-R"*|"-Q"*)
        if [ "$(id -u)" != "0" ]; then
            if [[ "$(which yay)" != "/usr/bin/yay" ]]; then
            installyay
            fi
            yay "${@:1}"
        else
            printf "${RED} Package management as root is very dangerous${NC}\n"
        fi

    ;;
    "-iso")
            source $extended/installer.sh
    ;;
    "-c"|"--crypto")
            source $extended/etc.sh
    ;;
    "n"|"network")
            source $extended/network.sh
    ;;
    "-rs"|"--repair-system")
        source $extended/update.sh
    ;;
    "t"|"theme")
        source $extended/theme.sh
    ;;    
    "b"|"bluetooth")
        source $extended/bluetooth.sh
    ;;
    "v"|"volume")
        source $extended/volume.sh
    ;;
    "s"|"screen")
        source $extended/screen.sh
    ;;
esac
