#!/bin/bash
# Shows the selected character in dunst if running.

# Must have xclip installed to even show menu.

chosen=$(grep -v "#" ~/.config/emoji | rofi -dmenu -font 'Fira Code 10' -p "Copy an emoji ")

[ "$chosen" != "" ] || exit

c=$(echo "$chosen" | sed "s/ .*//")
echo "$c" | tr -d '\n' | xclip -selection clipboard
notify-send "'$c' copied to clipboard." &

s=$(echo "$chosen" | sed "s/.*; //" | awk '{print $1}')
echo "$s" | tr -d '\n' | xclip
notify-send "'$s' copied to primary." &
