#!/bin/bash

dir=$(pwd)
out="To be determined"

while [ "$out" ];
do
        output=$(ls -a)
        out=$(echo -e "$output" | rofi -dmenu -font 'Fira Code 10' -i -p "Search your file")
        if [ -f "$out" ]; then
                open "$out"
        fi
        if [ -d "$out" ]; then
                cd "$out"                
        fi
done

cd "$dir"
